apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: tendermint-seed
  name: seed
subsets:
- addresses:
  - ip: "10.213.41.254"
  ports:
  - port: 27146
    name: p2p
  - port: 27147
    name: rpc
  - port: 26660
    name: prome
  - port: 8080
    name: api
